export enum EnumResponses {
  login = 'USER_LOGIN',
  logout = 'USER_LOGOUT',
  active = 'USER_ACTIVE',
  inactive = 'USER_INACTIVE',
  send = 'MSG_SEND',
  history = 'MSG_HISTORY',
  read = 'MSG_READ',
  edit = 'MSG_EDIT',
  delete = 'MSG_DELETE',
  deliver = 'MSG_DELIVER',
  count = 'MSG_COUNT',
  externalLogin = 'USER_EXTERNAL_LOGIN',
  externalLogout = 'USER_EXTERNAL_LOGOUT',
  error = 'ERROR',
}
